---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - name: 'Create EC2 instances with public IP'
      ec2_instance:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{aws_secret_key}}'
        name: "{{ item }}"
        region: '{{ region }}'
        key_name: munna
        vpc_subnet_id: '{{ vpc_subnet_id }}'
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: '{{ image_id }}'
        wait: yes
      with_items: 
        - target-1
        - target-2


